[2022-11-08T19:45:11.926+0900] {processor.py:156} INFO - Started process (PID=7492) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:45:11.926+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:45:11.927+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:45:11.927+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:45:11.935+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:45:11.935+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:45:11.935+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:45:11.935+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:45:11.936+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:45:11.942+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2022-11-08T19:45:45.440+0900] {processor.py:156} INFO - Started process (PID=7734) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:45:45.443+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:45:45.443+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:45:45.443+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:45:45.450+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:45:45.450+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:45:45.450+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:45:45.450+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:45:45.450+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:45:45.455+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:46:22.897+0900] {processor.py:156} INFO - Started process (PID=7811) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:46:22.900+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:46:22.900+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:46:22.900+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:46:22.907+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:46:22.907+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:46:22.907+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:46:22.907+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:46:22.907+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:46:22.912+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:47:03.856+0900] {processor.py:156} INFO - Started process (PID=7893) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:47:03.859+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:47:03.859+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:47:03.859+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:47:03.867+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:47:03.866+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:47:03.867+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:47:03.867+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:47:03.867+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:47:03.872+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T19:47:45.845+0900] {processor.py:156} INFO - Started process (PID=7934) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:47:45.847+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:47:45.847+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:47:45.847+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:47:45.855+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:47:45.855+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:47:45.855+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:47:45.855+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:47:45.855+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:47:45.860+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:48:23.269+0900] {processor.py:156} INFO - Started process (PID=7970) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:48:23.271+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:48:23.272+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:48:23.272+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:48:23.279+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:48:23.279+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:48:23.279+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:48:23.279+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:48:23.279+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:48:23.284+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:49:00.069+0900] {processor.py:156} INFO - Started process (PID=8006) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:49:00.071+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:49:00.072+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:49:00.072+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:49:00.079+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:49:00.079+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:49:00.079+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:49:00.079+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:49:00.079+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:49:00.084+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:49:39.718+0900] {processor.py:156} INFO - Started process (PID=8072) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:49:39.720+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:49:39.721+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:49:39.721+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:49:39.728+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:49:39.728+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:49:39.728+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:49:39.728+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:49:39.728+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:49:39.733+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:50:20.523+0900] {processor.py:156} INFO - Started process (PID=8112) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:50:20.525+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:50:20.525+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:50:20.525+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:50:20.532+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:50:20.532+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:50:20.532+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:50:20.532+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:50:20.532+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:50:20.537+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:51:02.553+0900] {processor.py:156} INFO - Started process (PID=8153) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:51:02.555+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:51:02.555+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:51:02.555+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:51:02.563+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:51:02.563+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:51:02.563+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:51:02.563+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:51:02.563+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:51:02.567+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:51:40.937+0900] {processor.py:156} INFO - Started process (PID=8190) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:51:40.939+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:51:40.940+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:51:40.940+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:51:41.013+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:51:41.013+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:51:41.013+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:51:41.013+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:51:41.013+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:51:41.017+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2022-11-08T19:52:14.883+0900] {processor.py:156} INFO - Started process (PID=8226) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:52:14.884+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:52:14.884+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:52:14.884+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:52:14.892+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:52:14.891+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:52:14.892+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:52:14.892+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:52:14.892+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:52:14.896+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T19:52:51.765+0900] {processor.py:156} INFO - Started process (PID=8310) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:52:51.766+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:52:51.767+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:52:51.766+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:52:51.774+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:52:51.774+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:52:51.774+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:52:51.774+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:52:51.775+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:52:51.779+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T19:53:29.074+0900] {processor.py:156} INFO - Started process (PID=8527) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:53:29.076+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:53:29.076+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:53:29.076+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:53:29.084+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:53:29.084+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:53:29.084+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:53:29.084+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:53:29.084+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:53:29.089+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:54:03.889+0900] {processor.py:156} INFO - Started process (PID=8583) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:54:03.891+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:54:03.891+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:54:03.891+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:54:03.899+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:54:03.898+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:54:03.899+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:54:03.899+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:54:03.899+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:54:03.903+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T19:54:40.685+0900] {processor.py:156} INFO - Started process (PID=8797) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:54:40.686+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:54:40.687+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:54:40.687+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:54:40.694+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:54:40.694+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:54:40.694+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:54:40.694+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:54:40.694+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:54:40.699+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T19:55:17.657+0900] {processor.py:156} INFO - Started process (PID=9016) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:55:17.657+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T19:55:17.658+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:55:17.658+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:55:17.665+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:55:17.665+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T19:55:17.665+0900] {logging_mixin.py:117} INFO - [2022-11-08T19:55:17.665+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T19:55:17.665+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T19:55:17.669+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2022-11-08T20:27:20.533+0900] {processor.py:156} INFO - Started process (PID=9810) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:27:20.535+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:27:20.535+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:27:20.535+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:27:20.543+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:27:20.543+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:27:20.543+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:27:20.543+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:27:20.544+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:27:20.548+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:27:57.308+0900] {processor.py:156} INFO - Started process (PID=9852) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:27:57.310+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:27:57.310+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:27:57.310+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:27:57.318+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:27:57.317+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:27:57.318+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:27:57.318+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:27:57.318+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:27:57.324+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2022-11-08T20:28:32.912+0900] {processor.py:156} INFO - Started process (PID=9898) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:28:32.914+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:28:32.915+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:28:32.915+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:28:32.922+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:28:32.922+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:28:32.922+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:28:32.922+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:28:32.922+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:28:32.927+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:29:08.656+0900] {processor.py:156} INFO - Started process (PID=10170) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:29:08.656+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:29:08.657+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:29:08.657+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:29:08.664+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:29:08.664+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:29:08.664+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:29:08.664+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:29:08.664+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:29:08.669+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T20:29:50.921+0900] {processor.py:156} INFO - Started process (PID=10363) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:29:50.921+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:29:50.922+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:29:50.922+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:29:50.930+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:29:50.929+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:29:50.930+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:29:50.930+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:29:50.930+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:29:50.935+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:30:29.281+0900] {processor.py:156} INFO - Started process (PID=10489) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:30:29.283+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:30:29.284+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:30:29.284+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:30:29.291+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:30:29.291+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:30:29.291+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:30:29.291+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:30:29.291+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:30:29.296+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:31:06.835+0900] {processor.py:156} INFO - Started process (PID=10645) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:31:06.836+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:31:06.836+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:31:06.836+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:31:06.844+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:31:06.843+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:31:06.844+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:31:06.844+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:31:06.844+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:31:06.850+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:31:50.480+0900] {processor.py:156} INFO - Started process (PID=10741) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:31:50.482+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:31:50.483+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:31:50.482+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:31:50.490+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:31:50.490+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:31:50.490+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:31:50.490+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:31:50.490+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:31:50.496+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2022-11-08T20:32:34.854+0900] {processor.py:156} INFO - Started process (PID=10902) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:32:34.857+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:32:34.857+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:32:34.857+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:32:34.864+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:32:34.864+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:32:34.864+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:32:34.864+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:32:34.864+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:32:34.869+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:33:10.653+0900] {processor.py:156} INFO - Started process (PID=10999) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:33:10.656+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:33:10.656+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:33:10.656+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:33:10.665+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:33:10.664+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:33:10.665+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:33:10.665+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:33:10.665+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:33:10.669+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:33:54.950+0900] {processor.py:156} INFO - Started process (PID=11040) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:33:54.951+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:33:54.951+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:33:54.951+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:33:55.043+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:33:55.043+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:33:55.043+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:33:55.043+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:33:55.043+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:33:55.047+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.099 seconds
[2022-11-08T20:34:30.537+0900] {processor.py:156} INFO - Started process (PID=11076) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:34:30.539+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:34:30.539+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:34:30.539+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:34:30.547+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:34:30.547+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:34:30.547+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:34:30.547+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:34:30.547+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:34:30.552+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:35:04.743+0900] {processor.py:156} INFO - Started process (PID=11112) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:35:04.746+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:35:04.746+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:35:04.746+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:35:04.753+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:35:04.753+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:35:04.753+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:35:04.753+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:35:04.753+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:35:04.757+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T20:35:42.456+0900] {processor.py:156} INFO - Started process (PID=11151) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:35:42.457+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:35:42.458+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:35:42.458+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:35:42.465+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:35:42.465+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:35:42.465+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:35:42.465+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:35:42.465+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:35:42.471+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:36:18.510+0900] {processor.py:156} INFO - Started process (PID=11188) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:36:18.512+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:36:18.512+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:36:18.512+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:36:18.520+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:36:18.519+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:36:18.520+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:36:18.520+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:36:18.520+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:36:18.525+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:36:53.332+0900] {processor.py:156} INFO - Started process (PID=11253) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:36:53.335+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:36:53.335+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:36:53.335+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:36:53.342+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:36:53.342+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:36:53.342+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:36:53.342+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:36:53.342+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:36:53.347+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:37:29.283+0900] {processor.py:156} INFO - Started process (PID=11290) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:37:29.285+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:37:29.285+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:37:29.285+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:37:29.292+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:37:29.292+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:37:29.292+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:37:29.292+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:37:29.292+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:37:29.297+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T20:38:04.814+0900] {processor.py:156} INFO - Started process (PID=11329) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:38:04.815+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:38:04.815+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:38:04.815+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:38:04.823+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:38:04.822+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:38:04.823+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:38:04.823+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:38:04.823+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:38:04.827+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.014 seconds
[2022-11-08T20:38:41.754+0900] {processor.py:156} INFO - Started process (PID=11367) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:38:41.756+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:38:41.756+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:38:41.756+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:38:41.764+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:38:41.764+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:38:41.764+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:38:41.764+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:38:41.764+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:38:41.768+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:39:16.898+0900] {processor.py:156} INFO - Started process (PID=11405) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:39:16.899+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:39:16.899+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:39:16.899+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:39:16.907+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:39:16.906+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:39:16.907+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:39:16.907+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:39:16.907+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:39:16.911+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T20:39:53.752+0900] {processor.py:156} INFO - Started process (PID=11441) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:39:53.754+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:39:53.754+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:39:53.754+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:39:53.763+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:39:53.763+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:39:53.764+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:39:53.764+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:39:53.764+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:39:53.769+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2022-11-08T20:40:31.686+0900] {processor.py:156} INFO - Started process (PID=11480) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:40:31.688+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:40:31.689+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:40:31.689+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:40:31.696+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:40:31.696+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:40:31.696+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:40:31.696+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:40:31.696+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:40:31.701+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:41:08.656+0900] {processor.py:156} INFO - Started process (PID=11519) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:41:08.658+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:41:08.659+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:41:08.659+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:41:08.666+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:41:08.666+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:41:08.666+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:41:08.666+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:41:08.667+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:41:08.672+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:41:47.483+0900] {processor.py:156} INFO - Started process (PID=11559) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:41:47.486+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:41:47.486+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:41:47.486+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:41:47.493+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:41:47.493+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:41:47.493+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:41:47.493+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:41:47.494+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:41:47.498+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:42:23.271+0900] {processor.py:156} INFO - Started process (PID=11625) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:42:23.273+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:42:23.273+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:42:23.273+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:42:23.280+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:42:23.280+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:42:23.281+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:42:23.281+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:42:23.281+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:42:23.285+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:42:59.900+0900] {processor.py:156} INFO - Started process (PID=11664) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:42:59.903+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:42:59.903+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:42:59.903+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:42:59.910+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:42:59.910+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:42:59.910+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:42:59.910+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:42:59.910+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:42:59.917+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2022-11-08T20:43:35.703+0900] {processor.py:156} INFO - Started process (PID=11700) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:43:35.704+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:43:35.704+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:43:35.704+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:43:35.712+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:43:35.712+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:43:35.712+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:43:35.712+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:43:35.712+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:43:35.718+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:44:09.578+0900] {processor.py:156} INFO - Started process (PID=11736) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:44:09.579+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:44:09.579+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:44:09.579+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:44:09.587+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:44:09.586+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:44:09.587+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:44:09.587+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:44:09.587+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:44:09.591+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T20:44:45.567+0900] {processor.py:156} INFO - Started process (PID=11774) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:44:45.569+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:44:45.570+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:44:45.570+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:44:45.578+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:44:45.578+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:44:45.578+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:44:45.578+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:44:45.578+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:44:45.583+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2022-11-08T20:45:24.498+0900] {processor.py:156} INFO - Started process (PID=11813) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:45:24.500+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:45:24.500+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:45:24.500+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:45:24.508+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:45:24.507+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:45:24.508+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:45:24.508+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:45:24.508+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:45:24.512+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:45:59.315+0900] {processor.py:156} INFO - Started process (PID=11850) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:45:59.317+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:45:59.317+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:45:59.317+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:45:59.326+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:45:59.326+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:45:59.326+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:45:59.326+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:45:59.326+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:45:59.331+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:46:40.294+0900] {processor.py:156} INFO - Started process (PID=11890) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:46:40.296+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:46:40.296+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:46:40.296+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:46:40.305+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:46:40.304+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:46:40.305+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:46:40.305+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:46:40.305+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:46:40.310+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:47:13.380+0900] {processor.py:156} INFO - Started process (PID=12038) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:47:13.382+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:47:13.382+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:47:13.382+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:47:13.391+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:47:13.390+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:47:13.391+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:47:13.391+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:47:13.391+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:47:13.395+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:47:50.158+0900] {processor.py:156} INFO - Started process (PID=12250) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:47:50.160+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:47:50.160+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:47:50.160+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:47:50.168+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:47:50.168+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:47:50.169+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:47:50.168+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:47:50.169+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:47:50.173+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
[2022-11-08T20:48:25.710+0900] {processor.py:156} INFO - Started process (PID=12286) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:48:25.712+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:48:25.713+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:48:25.712+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:48:25.722+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:48:25.721+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:48:25.722+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:48:25.722+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:48:25.722+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:48:25.727+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2022-11-08T20:48:59.856+0900] {processor.py:156} INFO - Started process (PID=12322) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:48:59.859+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:48:59.859+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:48:59.859+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:48:59.867+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:48:59.867+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:48:59.868+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:48:59.867+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:48:59.868+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:48:59.873+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2022-11-08T20:49:35.481+0900] {processor.py:156} INFO - Started process (PID=12359) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:49:35.482+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:49:35.482+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:49:35.482+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:49:35.489+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:49:35.489+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:49:35.489+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:49:35.489+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:49:35.489+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:49:35.494+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.015 seconds
[2022-11-08T20:50:11.547+0900] {processor.py:156} INFO - Started process (PID=12397) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:50:11.549+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:50:11.549+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:50:11.549+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:50:11.556+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:50:11.556+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:50:11.557+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:50:11.556+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:50:11.557+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:50:11.562+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.017 seconds
[2022-11-08T20:50:49.023+0900] {processor.py:156} INFO - Started process (PID=12591) to work on /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:50:49.025+0900] {processor.py:758} INFO - Processing file /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2022-11-08T20:50:49.025+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:50:49.025+0900] {dagbag.py:525} INFO - Filling up the DagBag from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:50:49.033+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:50:49.032+0900] {example_local_kubernetes_executor.py:39} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 37, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2022-11-08T20:50:49.033+0900] {logging_mixin.py:117} INFO - [2022-11-08T20:50:49.033+0900] {example_local_kubernetes_executor.py:40} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2022-11-08T20:50:49.033+0900] {processor.py:770} WARNING - No viable dags retrieved from /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2022-11-08T20:50:49.037+0900] {processor.py:178} INFO - Processing /home/steve/.local/lib/python3.8/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.016 seconds
